const fs = require('fs');
const path = require('path');

const MAX_FILES = 50;
const MAX_FILE_SIZE = 200 * 1024; // 200kb

const INCLUDED_EXTENSIONS = new Set(['.js', '.ts', '.jsx', '.tsx', '.py', '.json']);
const EXCLUDED_DIRS = new Set(['node_modules', '.git', 'dist', 'build', '.vscode', '.idea']);

/**
 * Strips the top-level directory wrapper generated by zips.
 * e.g., "repo-main/src/App.js" -> "src/App.js"
 */
function cleanRelativePath(relativeParts) {
    return relativeParts.join('/');
}

exports.traverseDirectory = (dirPath) => {
    let allFiles = [];
    let readmeContent = null;

    function walk(currentDir, relativeParts = []) {
        let list;
        try {
            list = fs.readdirSync(currentDir);
        } catch (e) { return; }

        for (const file of list) {
            const filePath = path.join(currentDir, file);
            let stat;
            try {
                stat = fs.statSync(filePath);
            } catch (e) { continue; }

            if (stat.isDirectory()) {
                if (!EXCLUDED_DIRS.has(file)) {
                    walk(filePath, [...relativeParts, file]);
                }
            } else {
                // detect readme
                if (!readmeContent && file.toLowerCase().includes('readme.md')) {
                    try {
                        const content = fs.readFileSync(filePath, 'utf8');
                        readmeContent = content.substring(0, 5000); // limit to first 5kb
                    } catch (e) { }
                }

                if (stat.size < 10) continue; // skip empty / tiny files

                const ext = path.extname(file).toLowerCase();
                if (INCLUDED_EXTENSIONS.has(ext)) {
                    allFiles.push({
                        absolutePath: filePath,
                        originalRelative: [...relativeParts, file],
                        extension: ext,
                        size: stat.size
                    });
                }
            }
        }
    }

    walk(dirPath, []);

    // sort files to prioritize `src/` and js/ts files
    allFiles.sort((a, b) => {
        const aPath = a.originalRelative.join('/');
        const bPath = b.originalRelative.join('/');

        const aIsSrc = aPath.includes('src/');
        const bIsSrc = bPath.includes('src/');
        if (aIsSrc && !bIsSrc) return -1;
        if (!aIsSrc && bIsSrc) return 1;

        const tsJsExts = ['.js', '.jsx', '.ts', '.tsx'];
        const aIsCode = tsJsExts.includes(a.extension);
        const bIsCode = tsJsExts.includes(b.extension);
        if (aIsCode && !bIsCode) return -1;
        if (!aIsCode && bIsCode) return 1;

        return b.size - a.size; // fallback to size
    });

    // select top limits
    const selectedFiles = allFiles.slice(0, MAX_FILES);

    // read contents
    const parsedFiles = selectedFiles.map(fileObj => {
        let content = '';
        try {
            const fd = fs.openSync(fileObj.absolutePath, 'r');
            const buffer = Buffer.alloc(Math.min(fileObj.size, MAX_FILE_SIZE));
            const bytesRead = fs.readSync(fd, buffer, 0, buffer.length, 0);
            content = buffer.toString('utf8', 0, bytesRead);
            fs.closeSync(fd);
        } catch (e) {
            content = 'ERROR_UNABLE_TO_READ_CONTENT';
        }

        const cleanedPath = cleanRelativePath(fileObj.originalRelative);

        return {
            path: cleanedPath,
            relativePath: cleanedPath,
            extension: fileObj.extension,
            size: fileObj.size,
            content: content
        };
    });

    return {
        files: parsedFiles,
        readme: readmeContent
    };
};
